post http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"3rd note created..."
}

###
put http://localhost:3001/api/notes/2
Content-Type: application/json

{
    "important":true
}


###
post http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"Jangbu",
    "name":"Jangbu Tamang"
}
###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"Jangbu",
    "password":"secret"
}